version: '3.7'

services:
  app:
    container_name: app
    restart: always
    build: ./app
    expose: 
      - 660
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"